apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      nodeSelector:
         env: test  # This targets the test-labeled node
      containers:
        - name: my-app
          image: sachinbacha/medicure:latest
          ports:
            - containerPort: 9090

---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: test
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - port: 80
      targetPort: 9090
      nodePort: 30090  # Test app accessible via http://<test-node-ip>:30090
